import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect } from 'react';

import Link from 'next/link';
import styles from '../styles/Home.module.css';

import Header from '../src/components/Header';

export default function Home() {
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <Header />

      {/* Main Content */}
      <main className={styles.main}>
        <section className={styles.topSection}>
          <p>SOUTHEAST ASIA FOCUSED PROGRAMS</p>

          <h1 className={styles.title}>
            Kickstart and accelerate your
            <br />
            early-stage investor journey
          </h1>

          <p>
            Powered by Insignia Ventures Partners, join and grow alongside a
            dynamic community of builders, founders, operators and investors.
            Start your journey to back great trailblazers today.
          </p>

          <div>
            <a>Explore our programs</a>
            <a>Get involved</a>
          </div>
        </section>

        {/* Call to Action Section */}
        <section className={styles.ctaSection}>
          <p>FEATURED RESOURCES</p>
          <h2>NEED A HAND?</h2>
          <p>
            Check out our free resources that help propel your startup or career
            forward.
          </p>

          <div className='container'>
            <p>FOUNDER RESOURCE</p>
          </div>
        </section>

        {/* 2nd Call to Action Section */}
        <section className={`${styles.ctaSection} ${styles.ctaSection2}`}>
          <p>NEXT</p>



          <Link
          href='/launchpad'
        >
          VENTURE CAPITAL LAUNCHPAD COURSE
        </Link>
        </section>
      </main>

      {/* Footer */}
      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
